---
name: Schedule

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/workflows/scheduler.yml
      - config/**
      - podsync/scheduler.py
      - podsync/refresh-opml.py
      - environment.yml
  schedule:
    - cron: 17 * * * *

permissions: write-all
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - uses: mamba-org/setup-micromamba@main
        name: Setup micromamba environment
        with:
          micromamba-version: latest
          environment-file: environment.yml
          environment-name: ci
          cache-environment: true
          cache-environment-key: ${{ hashFiles('**/environment.yml') }}
          cache-downloads: false
          log-level: info

      - name: Refresh OPML
        env:
          REPOSITORY: gabriel254/pods
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: micromamba-shell {0}
        run: |-
          # gh release download audio -D audio --clobber --pattern podsync.opml || true
          gh release download video -D video --clobber --pattern podsync.opml || true
          python podsync/refresh-opml.py

      - name: Sync
        env:
          REPOSITORY: ${{ github.repository }}  # run actions in this repo
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RSSHUB_URL: ${{ secrets.RSSHUB_URL }}
        shell: micromamba-shell {0}
        run: |-
          gh release download metadata -D metadata --clobber
          python podsync/scheduler.py --platform youtube --config config/youtube.json
          python podsync/scheduler.py --platform bilibili --config config/bilibili.json

  # https://github.com/liskin/gh-workflow-keepalive
  keepalive:
    if: github.event_name == 'schedule'
    name: Keepalive
    runs-on: ubuntu-latest
    permissions:
      actions: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Re-enable workflow
        run: |
          case "${GITHUB_WORKFLOW_REF:?}" in
          "${GITHUB_REPOSITORY:?}"/.github/workflows/*.y*ml@*) ;;
          *) false ;;
          esac
          workflow="${GITHUB_WORKFLOW_REF%%@*}"
          workflow="${workflow#${GITHUB_REPOSITORY}/.github/workflows/}"
          echo "Re-enable $workflow"
          gh api -X PUT "repos/${GITHUB_REPOSITORY}/actions/workflows/${workflow}/enable"
